Image upload
bobbydigital1986/salad-spot pull request #11
Opened 2023-05-10 20:16 UTC by meehanti23

Added AWS and image handling on salad post request

2023-05-10 20:27 UTC, bobbydigital1986 commented on client/src/components/SaladForm.js
>      const [shouldRedirect, setShouldRedirect] = useState(false)
It looks like shouldRedirect leverages a newSaladId - it should be set in defaults as well

2023-05-10 20:27 UTC, bobbydigital1986 commented on client/src/components/SaladForm.js
> +
Extra space

2023-05-10 20:42 UTC, bobbydigital1986 requested changes

2023-05-10 20:42 UTC, bobbydigital1986 commented on server/package.json
> +    "passport": "^0.6.0",
delete change?

2023-05-10 20:42 UTC, bobbydigital1986 commented on yarn.lock
> +  resolved "https://registry.npmjs.org/@ampproject/remapping/-/remapping-2.2.1.tgz"
@dovakeen118 npm hijacked tim's PR and we're not sure how to resolve :(

2023-05-11 17:06 UTC, nwalberts approved these changes
looks good!

2023-05-11 17:21 UTC, bobbydigital1986 approved these changes

2023-05-11 17:21 UTC, merged