Create index
bobbydigital1986/salad-spot pull request #2
Opened 2023-05-02 20:02 UTC by Jesspinoza

2023-05-02 20:33 UTC, dovakeen118 reviewed
work wise this looks great and is scoped well for the feature! the comments are super nit picking best practices following the JS style guide

2023-05-02 20:33 UTC, dovakeen118 commented on client/src/components/SaladListComponent.js
> +const SaladListComponent = (props) => {
should only have one empty line separating - can remove either line 3 or 4
https://github.com/airbnb/javascript#whitespace--no-multiple-blanks

2023-05-02 20:33 UTC, dovakeen118 commented on client/src/components/SaladListComponent.js
> +    const getSalads = async() =>{
should have a space before opening braces - `=> {`
https://github.com/airbnb/javascript#whitespace--before-blocks

should add a space before parenthesis - `async ()`
https://github.com/airbnb/javascript#whitespace--around-keywords

2023-05-02 20:33 UTC, dovakeen118 commented on client/src/components/SaladListComponent.js
> +        }catch(error){
spacing as well with try/catch braces

2023-05-02 20:33 UTC, dovakeen118 commented on client/src/components/SaladListComponent.js
> +        return (
can remove the empty line before the return
https://github.com/airbnb/javascript#whitespace--padded-blocks

2023-05-02 20:33 UTC, dovakeen118 commented on client/src/components/SaladListComponent.js
> +            salad={salad}
props should be indented within the component
```js
<SaladTile
  key={salad.id}
  salad={salad}
/>
```

2023-05-02 20:33 UTC, dovakeen118 commented on client/src/components/SaladTile.js
> +        <p>{description}</p>
`li` and `p` should be indented as they are children of the `div`

2023-05-02 20:33 UTC, dovakeen118 commented on client/src/components/SaladListComponent.js
> +        <ul>{saladItems}</ul>
the `h1` and `ul` should be indented as they are children of the `div`

consider changing the `ul` to a `div`, as an `ul` expects `li` elements as its children, but the `saladItems` are a collection of `div` elements

2023-05-02 20:33 UTC, dovakeen118 commented on server/src/db/Seeder.js
> +    const kale = await Salad.query().insert({ name: "Kale", userId: sally.id })
we should have separate seeders for each entity - UserSeeder, SaladSeeder, etc. Ideally should be set up to ensure duplicate records are not created if the seeder is run multiple times

2023-05-02 20:33 UTC, dovakeen118 commented on server/src/models/Salad.js
> +class Salad extends Model{
only one empty line for separation (lines 2 & 3)

2023-05-02 20:33 UTC, dovakeen118 commented on server/src/models/Salad.js
> +                description: {type: "string"}
info in braces should be space padded - `{ type: "string" }`
https://github.com/airbnb/javascript#whitespace--in-braces

2023-05-02 20:33 UTC, dovakeen118 commented on server/src/routes/api/v1/saladsRouter.js
> +    }catch (error){
spacing around try/catch braces
```js
try {
  ...
} catch (error) {
  ...
}
```

2023-05-03 15:31 UTC, nwalberts requested changes

2023-05-03 15:31 UTC, nwalberts commented on client/src/components/SaladListComponent.js
> +        </div>
this div isnt doing anything if it doesn have attributes. Delete it and replace with a React fragment e.g. `<></>`

2023-05-03 15:31 UTC, nwalberts commented on client/src/components/SaladListComponent.js
> +
delete this extra line

2023-05-03 15:31 UTC, nwalberts commented on client/src/components/SaladListComponent.js
> +
delete one of these two empty lines

2023-05-03 15:31 UTC, nwalberts commented on client/src/components/SaladTile.js
> +        </div>
this component looks like it still needs the indentation that Kerrin requested

Additionally, the div you have isnt doing anything, so please replace with a fragment

2023-05-03 15:31 UTC, nwalberts commented on server/src/models/Salad.js
> +    }
remove empty lines 31 and 33

2023-05-03 15:31 UTC, nwalberts commented on server/src/routes/api/v1/saladsRouter.js
> +
remove one empty line

2023-05-03 15:31 UTC, nwalberts commented on server/src/routes/rootRouter.js
> +
this empty line isnt needed, remove

2023-05-03 17:32 UTC, meehanti23 reviewed
looks good

2023-05-03 17:33 UTC, bobbydigital1986 reviewed
looks good

2023-05-03 17:33 UTC, merged